# Generated by Django 5.1 on 2024-09-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_field_company_field_of_work_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
