# Generated by Django 5.1 on 2024-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_birth_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100, unique=True),
        ),
    ]
