# Generated by Django 5.1 on 2024-09-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
