# Generated by Django 5.1 on 2024-09-10 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0006_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_field', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('service_time_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_services', to='users.company')),
            ],
        ),
    ]
