# Generated by Django 5.1 on 2024-09-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_requestedservice_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedservice',
            name='requested_by',
        ),
    ]
