# Generated by Django 5.1 on 2024-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_requestedservice_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedservice',
            name='service_name',
            field=models.CharField(default='new97', max_length=100),
            preserve_default=False,
        ),
    ]
