# Generated by Django 5.1 on 2024-09-14 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_requestedservice_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedservice',
            name='customer_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestedservice',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
