# Generated by Django 5.1 on 2024-09-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_requestedservice_customer_review_and_more'),
        ('users', '0006_company_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'company')},
        ),
    ]
